CHAT_MODEL = "llama-3.1-8b-instant"

REASONING_MODEL = "llama-3.3-70b-versatile"

CLASSIFICATION_MODEL = "llama-3.1-8b-instant"

TEMPERATURE = 0.2

MAX_TROUBLESHOOTING_ATTEMPTS = 5
DEFAULT_PROVIDER = "groq"